Numpy Notes

In [3]:
import numpy as np

In [5]:
print(np.__version__)

2.0.2


In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [74]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(matrix)
narr = np.array([1,2,3], ndmin=2)
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
print(mat.ndim)
print(narr.ndim)
print(narr.shape)

2
2
(1, 3)


In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.zeros(2)

array([0., 0.])

In [20]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Linspace
Return evenly spaced numbers over a specified interval.

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

### Random

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [25]:
np.random.randn(3)

array([-0.30087065, -1.13364116, -0.11914107])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [26]:
np.random.randn(3,3)

array([[-0.23985155,  1.49123186, -0.61847186],
       [-1.23464932, -0.76947111, -0.55146757],
       [-1.39499199,  0.29307537, -0.31568577]])

In [28]:
np.random.randint(1,100,3)

array([60,  2, 42])

In [39]:
ranarr = np.arange(5)
ranarr

array([0, 1, 2, 3, 4])

In [34]:
arr = np.random.randint(0,50,10)
arr

array([15,  1, 45, 20, 28, 34, 45, 35, 40, 48])

In [35]:
arr.reshape(5,2)

array([[15,  1],
       [45, 20],
       [28, 34],
       [45, 35],
       [40, 48]])

In [40]:
ranarr.max()

np.int64(4)

In [41]:
ranarr.argmax()

np.int64(4)

In [42]:
ranarr.min()

np.int64(0)

In [43]:
ranarr.argmin()

np.int64(0)

In [44]:
np.max(arr)

np.int64(48)

In [46]:
np.argmax(arr)

np.int64(9)

In [48]:
arr.dtype

dtype('int64')

In [59]:
newarr = np.random.randint(0,50,10).reshape(5,2)
newarr

array([[49,  3],
       [39, 38],
       [15,  2],
       [13, 42],
       [21, 15]])

In [60]:
newarr[2]

array([15,  2])

In [61]:
newarr[0:2]

array([[49,  3],
       [39, 38]])

In [62]:
newarr[:]

array([[49,  3],
       [39, 38],
       [15,  2],
       [13, 42],
       [21, 15]])

In [63]:
newarr[0][0]

np.int64(49)

In [64]:
newarr[0:2,0:2]

array([[49,  3],
       [39, 38]])

### Selection

In [65]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [68]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
%%sql


### Copy and View

In [81]:
ar1 = np.array([1,2,3,4,5])
x = ar1.copy()
ar1[0] = 42
print(ar1)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [83]:
ar2 = np.array([1,2,3,4,5])
y = ar2.view()
ar2[0] = 42
print(ar1)
print(y)

print(x.base)
print(y.base)

[42  2  3  4  5]
[42  2  3  4  5]
None
[42  2  3  4  5]


### Iterating Arrays

In [90]:
ite = np.array([1,2,3])
ite2 = np.array([[1, 2], [4, 5]])

for x in ite:
    print(x)

for x in ite2:
    print(x)

for x in ite2:
  for y in x:
    print(y)

1
2
3
[1 2]
[4 5]
1
2
4
5


In [91]:
for x in np.nditer(ite2):
  print(x)

1
2
4
5


Iterating Array With Different Data Types

In [92]:
for x in np.nditer(ite2, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'4')
np.bytes_(b'5')


### Joining NumPy Arrays

In [94]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

array3 = np.concatenate((array1, array2))
array3

array([1, 2, 3, 4, 5, 6])

Join two 2-D arrays along rows (axis=1):

In [99]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

array3 = np.concatenate((array1, array2), axis=1)
array3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Joining Arrays Using Stack Functions

In [105]:
a1 = np.array([1,2])
a2 = np.array([3,4])
a3 = np.stack((a1,a2),axis=1)
a3

array([[1, 3],
       [2, 4]])

NumPy provides a helper function: hstack() to stack along rows.

In [107]:
a4 = np.hstack((a1,a2))
a4

array([1, 2, 3, 4])

NumPy provides a helper function: vstack()  to stack along columns.

In [108]:
a5 = np.vstack((a1,a2))
a5

array([[1, 2],
       [3, 4]])

In [109]:
a6 = np.dstack((a1,a2))
a6

array([[[1, 3],
        [2, 4]]])

### Splitting NumPy Arrays

In [113]:
ax = np.array([1,2,3,4,5,6])
newone = np.array_split(ax,3)
newone

[array([1, 2]), array([3, 4]), array([5, 6])]

In [114]:
newone[1]

array([3, 4])

### Searching Arrays

In [125]:
arx = np.array([1,9, 2, 3, 4, 5, 4, 4])

x = np.where(arx == 4)
x

(array([4, 6, 7]),)

In [127]:
y = np.where(arx%2 == 0)
y

(array([2, 4, 6, 7]),)

In [128]:
x = np.searchsorted(arx,3)
x

np.int64(3)

In [130]:
argx = np.array([1, 3, 5, 7])

arggx = np.searchsorted(argx, [2, 4, 6])
arggx

array([1, 2, 3])

In [133]:
argy = np.array([9, 3, 4, 7, 1])

np.sort(argy)

array([1, 3, 4, 7, 9])